my_app/urls.py
from django.conf.urls import url
from my_app import views

app_name = 'my_app'

urlpatterns = [
    url(r'^relative/', views.relative, name="relative"),
    url(r'^other/', views.other, name="other"),
    url(r'^register/', views.register, name="register"),
    url(r'^signin/', views.signin, name="signin"),
    url(r'^my_admin/$', views.my_admin, name="my_admin")
]

mysite/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from my_app import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^my_app/', include('my_app.urls'))
]

my_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    
    def __str__(self):
        return self.user.username

my_app/forms.py
from django.contrib.auth.models import User
from my_app.models import UserProfileInfo
from django import forms
from django.forms import fields


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    
    class Meta():
            model = User
            fields = ["username", "email", "password"]
        
class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ["portfolio_site", "profile_pic"]
        
class SignInForm(forms.ModelForm):
    class Meta():
            model = User
            fields = ["username", "password"]

my_app/views.py
from django.shortcuts import render
from my_app.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request,'my_app/index.html')

@login_required
def user_logout(request):
       logout(request)
       return HttpResponseRedirect(reverse('index'))

def relative(request):
       return render(request, 'my_app/relative.html')

def my_admin(request):
       return render(request,'my_app/my_admin.html')

def signin(request):
       if request.method == 'POST':
              username = request.POST.get('username')
              password = request.POST.get('password')
              
              user = authenticate(username=username,password=password)

              if user:
                     if user.is_active:
                            login(request,user)
                            return HttpResponse(reverse('index'))
                     else:
                            return HttpResponse('Account not active')
              else:
                     print('someone tried to login')
                     print(username,password)
                     return HttpResponse('invalid login')
     
       else:
         return  render(request, 'my_app/signin.html', {})
              

def other(request):
       return render(request,'my_app/other.html')


def  register(request):
       
       registered = False
       
       if request.method == 'POST':
                            
              user_form = UserForm(data=request.POST)
              profile_form = UserProfileForm(data=request.POST)
              
              if user_form.is_valid() and profile_form.is_valid():
                     user = user_form.save()
                     user.set_password(user.password)
                     user.save()
                     
                     profile = profile_form.save(commit=False)
                     profile.user = user
                     
                     if 'profile_pic' in request.FILES:
                            profile.profile_pic = request.FILES['profile_pic']
                            
                            profile.save()
                            
                            registered = True
              else:
                     print(user_form.errors, profile_form.errors)
       else:
              user_form = UserForm
              profile_form = UserProfileForm()
       return render(request, 'my_app/registration.html', 
                     {'user_form':user_form,'profile_form':profile_form,'registered':registered})     
       

templates/my_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body >
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <div class="container">
            <ul class="nav navbar-nav navbar">
                <li><a class="navbar-brand" href="{% url 'index'%}">Lexicon</a></li>
                <li><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class="nav-link" href="{% url 'my_app:register' %}">Register</a></li>
                
                {%if user.is_authenticated%}
                        <li><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                {%else%}
                <li><a class="nav-link" href="{% url 'my_app:signin' %}">Sign In</a></li>
                {%endif%}

            </ul>
        </div>
    </nav>
    <div class="container">
        
        {% block body_block%}
        
        {% endblock %}

    </div>
    <footer class="page-footer font-small purple pt-4 fixed-bottom">

        <!-- Footer Links -->
       
            <!-- Grid column -->
    
           
        <!-- Footer Links -->
    
        <!-- Copyright -->
        <div class="footer-copyright text-center py-3">© 2021 Copyright John Chimbani
        </div>
        <!-- Copyright -->
    
      </footer>
</body>
</html>

templates/my_app/index.html
{% extends 'my_app/base.html' %}
{% block body_block %}

<h1>Index Page</h1>


{% endblock %}

templates/my_app/login.html
{% extends 'my_app/base.html' %}
{% block body_block %}
<h1 class="text-center">Login!</h1>
<div class="jumbotron text-center">
    <h2> Please Login</h2>
</div>


 {% endblock %}

templates/my_app/my_admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body class="container">
    <div class="jumbotron">
       <h1> Welcome to admin page!</h1>
    </div>
    
</body>
</html>

templates/my_app/other.html
{% extends 'my_app/base.html' %}
{% block body_block %}
<h1> Welcome to Other!</h1>


<h2> This is an ex of template inheritance!</h2>
 {% endblock %}

templates/my_app/registration.html
{% extends 'my_app/base.html' %}

{%load static %}

{%block body_block %}
<div class="jumbotron">
    {%if registered %}
    <h1 class="text-center">Thank you for Registering</h1>
    {%else%}
    <h1 >Rigister here!</h1>

        <h3>Fill out this form</h3>
        <form enctype="multipart/form-data" method="POST">
        {%csrf_token%}
        {{user_form.as_p}}
        {{profile_form.as_p}}

        <input type="submit" name="" value="Register">
        </form>
    {%endif%}
</div>
{%endblock%}

templates/my_app/relative.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body class="container">
    <div class="jumbotron">
       <h1> Welcome to relativ html page!</h1>
       <a href="{% url 'my_app:other'%}"> Other</a>
        <a href="{% url 'admin:index'%}"> Admin</a>
    </div>
    
</body>
</html>

templates/my_app/signin.html
{% extends 'my_app/base.html' %}
{%block body_block %}
<div class="jumbotron">
   
    <h1 class="text-center">Sign In</h1>
          
        <form action="{%url 'my_app:signin'%}" method="POST">
        {%csrf_token%}
     
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter username"></input>
        <label for="password">Pasword:</label>
        <input type="password" name="password" placeholder="Enter password"></input>

        <input type="submit" value="Sign In">
        </form>
</div>
{%endblock%}